feat(actions): use aws ecr for openapi-generator image
moneymeets/openapi-generator pull request #17
Opened 2023-03-28 09:55 UTC by mm-ivanovig

### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ ] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

use AWS ECR for openapi-generator image instead of DockerHub

2023-03-28 11:07 UTC, marns93 requested changes
:+1: 
Your changes looks good to me. You can update the other parts of the workflow to fix the warning with Nodejs 12 and remove `name` key to follow our convention.
Thank you. :)

2023-03-28 11:07 UTC, marns93 commented on .github/workflows/moneymeets-ci.yml
>          run: docker build -t $DOCKER_REGISTRY:$TAG .
```suggestion
      - run: docker build -t $DOCKER_REGISTRY:$TAG .
```

2023-03-28 11:07 UTC, marns93 commented on .github/workflows/moneymeets-ci.yml
>        - uses: actions/checkout@v2
```suggestion
      - uses: actions/checkout@v3
```

2023-03-28 11:07 UTC, marns93 commented on .github/workflows/moneymeets-ci.yml
>        - name: Publish image
I think the name can be removed as well

2023-03-28 11:10 UTC, marns93 commented
@mm-ivanovig Please push the manual created images from DockerHub to ECR as well:
https://github.com/search?q=org%3Amoneymeets+moneymeets%2Fopenapi-generator&type=code

2023-03-28 11:24 UTC, mm-ivanovig commented
> @mm-ivanovig Please push the manual created images from DockerHub to ECR as well: https://github.com/search?q=org%3Amoneymeets+moneymeets%2Fopenapi-generator&type=code

Pushed latest tag
Also I think easier to push backend images manually (amd64/arm64) - because for arm we need to check how to build them automatically. And also we need to upload manifest to the ECR for multi-arch images. 

@marns93 
Does it make sense to create a separate ticket for backend images upload automation?

2023-03-28 12:19 UTC, marns93 commented
> > @mm-ivanovig Please push the manual created images from DockerHub to ECR as well: https://github.com/search?q=org%3Amoneymeets+moneymeets%2Fopenapi-generator&type=code
> 
> Pushed latest tag Also I think easier to push backend images manually (amd64/arm64) - because for arm we need to check how to build them automatically. And also we need to upload manifest to the ECR for multi-arch images.

Thank you
> @marns93 Does it make sense to create a separate ticket for backend images upload automation?

Yes, I think we should do this.

2023-03-28 12:21 UTC, marns93 approved these changes
:+1:

2023-03-28 12:23 UTC, merged

2023-03-28 16:33 UTC, zyv commented
@marns93 @mm-ivanovig 

https://buildjet.com/for-github-actions/docs/guides/arm

They support native ARM64 runners and claim to offer much faster hardware for cheaper price. Do you want to try it?

2023-03-29 06:57 UTC, marns93 commented
> @marns93 @mm-ivanovig
> 
> https://buildjet.com/for-github-actions/docs/guides/arm
> 
> They support native ARM64 runners and claim to offer much faster hardware for cheaper price. Do you want to try it?

Sure, we can do this. @mm-ivanovig Created a ticket https://moneymeets.atlassian.net/browse/MD-6711 yesterday and I added your link.